-- Seeds a broad starting Tag vocabulary (see CONTEXT.md: Tag, Tag Group).
-- Household-extensible from here on; this just lays the initial groundwork.

INSERT OR IGNORE INTO `tags` (`name`, `tag_group`) VALUES
	('gluten', 'allergen'),
	('dairy', 'allergen'),
	('egg', 'allergen'),
	('fish', 'allergen'),
	('shellfish', 'allergen'),
	('tree-nut', 'allergen'),
	('peanut', 'allergen'),
	('soy', 'allergen'),
	('sesame', 'allergen'),
	('mustard', 'allergen'),
	('celery', 'allergen'),
	('lupin', 'allergen'),
	('sulphite', 'allergen'),
	('mollusc', 'allergen'),
	('vegan', 'diet'),
	('vegetarian', 'diet'),
	('pescatarian', 'diet'),
	('gluten-free', 'diet'),
	('dairy-free', 'diet'),
	('nut-free', 'diet'),
	('low-carb', 'diet'),
	('keto', 'diet'),
	('paleo', 'diet'),
	('halal', 'diet'),
	('kosher', 'diet'),
	('low-fodmap', 'diet'),
	('creamy', 'sensory'),
	('crunchy', 'sensory'),
	('crispy', 'sensory'),
	('chewy', 'sensory'),
	('spicy', 'sensory'),
	('sweet', 'sensory'),
	('sour', 'sensory'),
	('bitter', 'sensory'),
	('umami', 'sensory'),
	('acidic', 'sensory'),
	('smoky', 'sensory'),
	('tangy', 'sensory');
